#eureka server服务端口
server:
  port: 8762


spring:
  application:
    name: lagou-eureka-server # 应用名称，应用名称会在Eureka中作为服务名称

# eureka 客户端配置（和Server交互），Eureka Server 其实也是一个Client
eureka:
  instance:
    hostname: localhost  # 当前eureka实例的主机名
    #使⽤ip注册，否则会使⽤主机名注册了（此处考虑到对⽼版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
    #⾃定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}:@project.version@
  client:
    service-url:
      # 配置客户端所交互的Eureka Server的地址（Eureka Server集群中每一个Server其实相对于其它Server来说都是Client）
      # 集群模式下，defaultZone应该指向其它Eureka Server，如果有更多其它Server实例，逗号拼接即可
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true  # 自己就是server 不用注册
    fetch-registry: true        # 查询获取注册中心的服务信息，自己就是server不需要从server获取服务信息 默认为true
  #dashboard:
  #  enabled: true
